---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: frr
tags: [routing, networking, facts]
namespace: frr
readme: README.md
description: Ansible Collection for Free Range Routing (FRR).
repository: https://github.com/ansible-collections/frr.frr
