---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.6.1"
license_file: LICENSE
name: frr
tags: [routing, networking, facts, frr]
namespace: frr
readme: README.md
description: Ansible Collection for Free Range Routing (FRR).
repository: https://github.com/ansible-collections/frr.frr
issues: https://github.com/ansible-collections/frr.frr/issues
version: "2.0.3-dev"
