---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: skydive
namespace: skydive
readme: README.rst
repository: https://github.com/ansible-collections/skydive
