objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf:
    frr:
      description: Use frr cliconf to run command on Free Range Routing platform
      name: frr
      version_added: 1.0.0
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    frr_bgp:
      description: Configure global BGP settings on Free Range Routing(FRR).
      name: frr_bgp
      namespace: ''
      version_added: 1.0.0
    frr_facts:
      description: Collect facts from remote devices running Free Range Routing (FRR).
      name: frr_facts
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 2.0.0
